//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Butik
    {
        public Butik()
        {
            this.Radniks = new HashSet<Radnik>();
            this.Proizvods = new HashSet<Proizvod>();
            this.Kasas = new HashSet<Kasa>();
        }
    
        public int PIB { get; set; }
        public string Naziv { get; set; }
        public string Adresa { get; set; }
    
        public virtual ICollection<Radnik> Radniks { get; set; }
        public virtual ICollection<Proizvod> Proizvods { get; set; }
        public virtual ICollection<Kasa> Kasas { get; set; }
    }
}
