//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kasa
    {
        public Kasa()
        {
            this.Racuns = new HashSet<Racun>();
        }
    
        public int IdKase { get; set; }
        public Nullable<int> ButikPIB { get; set; }
    
        public virtual Butik Butik { get; set; }
        public virtual ICollection<Racun> Racuns { get; set; }
    }
}
