//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kupuje
    {
        public int ID { get; set; }
        public int KupacIdKupca { get; set; }
        public int ProizvodKodProizvoda { get; set; }
        public int RacunIdRacuna { get; set; }
    
        public virtual Racun Racun { get; set; }
        public virtual Proizvod Proizvod { get; set; }
        public virtual Kupac Kupac { get; set; }
    }
}
