//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menadzer
    {
        public Menadzer()
        {
            this.Radniks = new HashSet<Radnik>();
        }
    
        public int JMBGMenadzera { get; set; }
    
        public virtual ICollection<Radnik> Radniks { get; set; }
    }
}
