//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container1 : DbContext
    {
        public Model1Container1()
            : base("name=Model1Container1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Butik> Butiks { get; set; }
        public DbSet<Kasa> Kasas { get; set; }
        public DbSet<Radnik> Radniks { get; set; }
        public DbSet<Racun> Racuns { get; set; }
        public DbSet<Proizvod> Proizvods { get; set; }
        public DbSet<Kupac> Kupacs { get; set; }
        public DbSet<Kupuje> Kupujes { get; set; }
        public DbSet<Prodavac> Prodavacs { get; set; }
        public DbSet<Menadzer> Menadzers { get; set; }
    }
}
