//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvod
    {
        public int KodProizvoda { get; set; }
        public int Cijena { get; set; }
        public string NazivProizvoda { get; set; }
        public Nullable<int> ButikPIB { get; set; }
    
        public virtual Butik Butik { get; set; }
    }
}
