//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        public int IdRacuna { get; set; }
        public int Ukupno { get; set; }
        public int KasaIdKase { get; set; }
    
        public virtual Kasa Kasa { get; set; }
    }
}
