//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radnik
    {
        public int JMBG { get; set; }
        public string ImeRadnika { get; set; }
        public string PrezimeRadnika { get; set; }
        public string TipRadnika { get; set; }
        public int ButikPIB { get; set; }
    
        public virtual Butik Butik { get; set; }
        public virtual Menadzer Menadzer { get; set; }
        public virtual Prodavac Prodavac { get; set; }
    }
}
